---
- name: 1st Play of Cloud
  become: yes
  become_method: sudo
  hosts: cloud
  gather_facts: true
  tasks:
    - name: Installing apache package
      package: name=apache2 state=present
      register: apache_out
      ignore_errors: true
      when: ansible_distribution == "Ubuntu"
      tags:
        - package
        - dev
        - prod
    - name: start the service
      service: name=apache2 state=started
      when: ansible_distribution == "Ubuntu"
      tags:
        - service
        - dev
    - name: Installing httpd package
      package: name=httpd state=present
      when: ansible_distribution == "CentOS"
      tags:
        - package
        - prod
    - name: Importing tasks IMPORT TASKS
      import_tasks: ./ntp.yml

    - name: start web service on Centos
      service: name=httpd state=started
      when: ansible_distribution == "CentOS"
      tags:
        - service
        - prod
- name: Second Play started for IMPORT PLAYBOOK
  import_playbook: ./variable.yml
