---
- name: re-Iteration
  hosts: host01
  become: yes
  become_method: sudo
  gather_facts: true
  tasks:
    - name: create multiple users
      user: name={{ item }} state=absent
      with_lines: cat /root/playbooksDir/users.txt
