---
- name: re-Iteration
  hosts: cloud
  become: yes
  become_method: sudo
  gather_facts: true
  tasks:
    - name: print values
      command: echo "{{item}}"
      loop: [ 0, 2, 4, 6, 8, 10 ]
      when: item > 5
