---
- name: Uninstall Java and Tomcat from servers
  hosts: cloud 
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: true
  tasks:
     - name: Pre-requisite for tomcat to ensure sample.war is absent
       file: path=/opt/tomcat/apache-tomcat-8.5.29/webapps/sample.war state=absent
     - name: Uninstall jdk
       yum: name=java-1.8.0-openjdk state=absent
     - name: Install wget on the servers
       yum: name=wget state=present
     - name: Create directory for tomcat
       file: name=/opt/tomcat state=directory
     - name: Uninstall tomcat package
       shell: cd /opt/tomcat; rm -rf apache-tomcat-8.5.73.zip; rm -rf apache-tomcat-8.5.73
