---
- name: first play for variable test
  hosts: host02
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false
  vars:
    user1: gagandeep
    user2: ""
  tasks:
    - name: Creating user {{ user1 }} on all machines
      user: name={{ user1 }} state=present
    - name: creating user {{ user2 }}
      user:
        name: "{{ user2 }}"
        state: present
