---
- name: play1
  hosts: cloud
  become: yes
  become_method: sudo
  tasks:
    - name: create users on all machines
      user:
         name: "{{item}}"
         state: present
      with_items:
         - user11
         - user12
         - user13
      
